server:
  port: 8762
spring:
  datasource:
   url: jdbc:mysql://127.0.0.1:3306/testsystem?useUnicode=true&characterEncoding=utf-8
   username: root
   password: 123456
   driver-class-name: com.mysql.jdbc.Driver

#mybatis:
    #mapper-locations: classpath:mapper/*Mapper.xml
    #type-aliases-package: com.arryluo.springbootmybatisplus.entity
    #configuration:
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.arryluo.springbootmybatisplus.entity


